# Generated by Django 5.0 on 2023-12-24 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tweet',
        ),
        migrations.AddField(
            model_name='comment',
            name='curr_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_tweet', to='account.tweet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_tweet', to='account.tweet'),
        ),
    ]
