# Generated by Django 5.0 on 2023-12-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_comment_tweet_comment_curr_tweet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Retweet',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
