# Generated by Django 5.0 on 2023-12-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_like_tweet_remove_like_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
